### ISSUE TITLE
Wrong chapter number in tirmidhi

### ISSUE THREAD

**Issue by unkn4wn** [jarfile/hadithdb#3]
Asselamu Aleykum, 
The chapter number and the chapter name seems to be wrong in Jamiʿ al-Tirmidhī. Odd duplicates.

![image](https://user-images.githubusercontent.com/103898825/210582752-ff12f01b-03cf-4b9f-98b9-703db7eb2dd6.png)

**Comment by unkn4wn** [comment]
Another small mistake can be found in Sahih Muslim. 2675h is wrong. And maybe mentioning 2675 in C48 as first hadith number would be a more user friendly approach than mentioning "2675a" 
![image](https://user-images.githubusercontent.com/103898825/210584825-99b42e82-577c-4226-a7dc-b110c097d076.png)

**Comment by unkn4wn** [comment]
Another minor mistake in Sahih Bukhari. The row which contains 931 can be removed.
![image](https://user-images.githubusercontent.com/103898825/210585754-515dfb7c-43b1-49d4-aaed-e01e32cc78c9.png)

**Comment by iadnanmukhtar** [comment]
jazāk Allāh khayran for your feedback. I will look into this as soon as possible.
